name: tekaly_playlr_assets
description: Playlr assets
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.0

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ">=5.0.0"
  test: ">=1.24.0"
resolution: workspace
