name: tekaly_playlr_assets
description: Playlr assets
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.0

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: '>=2.0.0'
  test: '>=1.16.0'
resolution: workspace
