name: tekartik_file_cache
description: A starting point for Dart libraries or applications.
version: 1.0.1
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  path: ">=1.9.0"
  sembast: ">=3.7.4+3"
  fs_shim: ">=2.3.3+1"
  tekartik_app_http:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      ref: dart3a
      path: app_http
    version: '>=0.1.0'
  tekartik_app_cv_sembast:
    git:
      url: https://github.com/tekartik/app_common_utils.dart
      ref: dart3a
      path: app_cv_sembast
    version: '>=0.5.0'
dev_dependencies:
  lints: ">=5.0.0"
  test: ">=1.24.0"
resolution: workspace
