name: playlr_audio_player_interface
description: Audio player interface
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: '>=2.0.0'
  test: '>=1.21.0'
resolution: workspace
